# Generated by Django 5.2.7 on 2025-10-14 02:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from datetime import timedelta



class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_agregar_categoria_agregar_datos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agregar_datos',
            name='duracion',
            field=models.DurationField(default=timedelta(hours=1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agregar_datos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.agregar_categoria'),
        ),
        migrations.AlterField(
            model_name='agregar_datos',
            name='tiempo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
